// src/design-system/components/Button.vue
<script setup lang="ts">
interface Props {
  variant?: 'primary' | 'secondary' | 'ghost' | 'danger'
  size?: 'sm' | 'md' | 'lg'
  disabled?: boolean
  loading?: boolean
}

withDefaults(defineProps<Props>(), {
  variant: 'primary',
  size: 'md',
  disabled: false,
  loading: false,
})
</script>

<template>
  <button
    :class="[
      'brutal-btn',
      `brutal-btn--${variant}`,
      `brutal-btn--${size}`,
      {
        'brutal-btn--disabled': disabled,
        'brutal-btn--loading': loading,
      }
    ]"
    :disabled="disabled || loading"
  >
    <span v-if="loading" class="brutal-btn__spinner" />
    <slot />
  </button>
</template>

<style scoped>
.brutal-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: var(--space-2);
  font-family: var(--font-display);
  font-weight: var(--font-weight-bold);
  border: var(--border-width) solid var(--button-border);
  cursor: pointer;
  user-select: none;
  white-space: nowrap;
  position: relative;
  box-shadow: 4px 4px 0 0 var(--button-shadow);
  transition: transform var(--duration-fast) var(--ease),
              box-shadow var(--duration-fast) var(--ease),
              background-color var(--duration-fast) var(--ease),
              color var(--duration-fast) var(--ease),
              border-color var(--duration-fast) var(--ease);
}

.brutal-btn:hover:not(:disabled) {
  transform: translate(2px, 2px);
  box-shadow: 2px 2px 0 0 var(--button-shadow);
}

.brutal-btn:active:not(:disabled) {
  transform: translate(4px, 4px);
  box-shadow: none;
}

.brutal-btn:focus-visible {
  outline: 3px solid var(--color-focus-ring);
  outline-offset: 2px;
}

/* ── Sizes ── */
.brutal-btn--sm {
  height: 2.25rem;
  padding: 0 var(--space-4);
  font-size: var(--text-sm);
}

.brutal-btn--md {
  height: 2.75rem;
  padding: 0 var(--space-6);
  font-size: var(--text-base);
}

.brutal-btn--lg {
  height: 3.25rem;
  padding: 0 var(--space-8);
  font-size: var(--text-lg);
}

/* ── Variants ── */
.brutal-btn--primary {
  background-color: var(--button-primary-bg);
  color: var(--button-primary-text);
}

.brutal-btn--primary:hover:not(:disabled) {
  background-color: var(--button-primary-hover);
}

.brutal-btn--secondary {
  background-color: var(--button-secondary-bg);
  color: var(--button-secondary-text);
}

.brutal-btn--secondary:hover:not(:disabled) {
  background-color: var(--button-secondary-hover);
}

.brutal-btn--ghost {
  background-color: var(--button-ghost-bg);
  color: var(--button-ghost-text);
}

.brutal-btn--ghost:hover:not(:disabled) {
  background-color: var(--button-ghost-hover);
}

.brutal-btn--danger {
  background-color: var(--button-danger-bg);
  color: var(--button-danger-text);
}

.brutal-btn--danger:hover:not(:disabled) {
  background-color: var(--button-danger-hover);
}

/* ── States ── */
.brutal-btn--disabled {
  opacity: 0.45;
  cursor: not-allowed;
}

.brutal-btn--loading {
  pointer-events: none;
}

/* ── Spinner ── */
.brutal-btn__spinner {
  width: 1em;
  height: 1em;
  border: 2px solid currentColor;
  border-top-color: transparent;
  border-radius: 0;
  animation: brutal-spin 0.6s linear infinite;
}

@keyframes brutal-spin {
  to { transform: rotate(360deg); }
}
</style>

// apps/web/src/components/ui/button.tsx
'use client'

import { forwardRef, type ButtonHTMLAttributes } from 'react'
import { cn } from '@/lib/cn'

type Variant = 'primary' | 'secondary' | 'ghost' | 'danger'
type Size = 'sm' | 'md' | 'lg'

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: Variant
  size?: Size
  loading?: boolean
  block?: boolean
}

const variantStyles: Record<Variant, string> = {
  primary:
    'bg-[var(--button-primary-bg)] text-[var(--button-primary-text)] hover:bg-[var(--button-primary-hover)]',
  secondary:
    'bg-[var(--button-secondary-bg)] text-[var(--button-secondary-text)] hover:bg-[var(--button-secondary-hover)]',
  ghost:
    'bg-[var(--button-ghost-bg)] text-[var(--button-ghost-text)] hover:bg-[var(--button-ghost-hover)]',
  danger:
    'bg-[var(--button-danger-bg)] text-[var(--button-danger-text)] hover:bg-[var(--button-danger-hover)]',
}

const sizeStyles: Record<Size, string> = {
  sm: 'min-h-[2.4rem] px-[0.9rem] py-1 text-sm',
  md: 'min-h-[2.95rem] px-[1.2rem] py-2 text-base',
  lg: 'min-h-[3.4rem] px-[1.4rem] py-2.5 text-lg',
}

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  (
    {
      variant = 'primary',
      size = 'md',
      loading,
      disabled,
      block,
      className,
      children,
      ...props
    },
    ref,
  ) => (
    <button
      ref={ref}
      disabled={disabled || loading}
      className={cn(
        'relative inline-flex items-center justify-center gap-[0.55rem]',
        'font-[family-name:var(--font-display)] font-bold tracking-[0.005em] leading-tight',
        'border border-[var(--button-border)] rounded-[var(--radius-md)]',
        'shadow-[var(--shadow-brutal-sm)] cursor-pointer select-none overflow-hidden',
        'transition-[box-shadow,opacity,background-color,border-color] duration-[var(--duration-fast)]',
        'hover:shadow-[var(--shadow-brutal)] hover:opacity-[0.92]',
        'active:shadow-[var(--shadow-brutal-sm)] active:opacity-[0.85]',
        'focus-visible:outline-none focus-visible:shadow-[var(--focus-ring-shadow)]',
        'disabled:opacity-55 disabled:cursor-not-allowed disabled:shadow-none disabled:border-[var(--color-border-subtle)]',
        variantStyles[variant],
        sizeStyles[size],
        block && 'w-full',
        className,
      )}
      {...props}
    >
      {loading && (
        <span
          className="w-[0.9rem] h-[0.9rem] border-2 border-current border-r-transparent rounded-full animate-spin"
          aria-hidden="true"
        />
      )}
      {children}
    </button>
  ),
)

Button.displayName = 'Button'
