// src/design-system/components/Card.vue
<script setup lang="ts">
interface Props {
  interactive?: boolean
  elevated?: boolean
  padding?: 'none' | 'sm' | 'md' | 'lg'
  accent?: 'coral' | 'turquoise' | 'yellow' | null
}

withDefaults(defineProps<Props>(), {
  interactive: false,
  elevated: false,
  padding: 'md',
  accent: null,
})
</script>

<template>
  <div
    :class="[
      'brutal-card',
      `brutal-card--padding-${padding}`,
      {
        'brutal-card--interactive': interactive,
        'brutal-card--elevated': elevated,
        'brutal-card--accent-coral': accent === 'coral',
        'brutal-card--accent-turquoise': accent === 'turquoise',
        'brutal-card--accent-yellow': accent === 'yellow',
      }
    ]"
  >
    <slot />
  </div>
</template>

<style scoped>
.brutal-card {
  background-color: var(--color-surface);
  border: var(--border-width) solid var(--color-border-strong);
  box-shadow: var(--shadow-brutal);
  transition: transform var(--duration-fast) var(--ease),
              box-shadow var(--duration-fast) var(--ease);
}

/* ── Interactive hover ── */
.brutal-card--interactive {
  cursor: pointer;
}

.brutal-card--interactive:hover {
  transform: translate(2px, 2px);
  box-shadow: var(--shadow-brutal-sm);
}

.brutal-card--interactive:active {
  transform: translate(4px, 4px);
  box-shadow: none;
}

/* ── Elevated — bigger shadow ── */
.brutal-card--elevated {
  box-shadow: var(--shadow-brutal-lg);
}

.brutal-card--elevated:hover {
  box-shadow: var(--shadow-brutal);
}

/* ── Padding ── */
.brutal-card--padding-none { padding: 0; }
.brutal-card--padding-sm { padding: var(--space-4); }
.brutal-card--padding-md { padding: var(--space-6); }
.brutal-card--padding-lg { padding: var(--space-8); }

/* ── Color accent strips ── */
.brutal-card--accent-coral { border-left: 8px solid var(--color-coral); }
.brutal-card--accent-turquoise { border-left: 8px solid var(--color-turquoise); }
.brutal-card--accent-yellow { border-left: 8px solid var(--color-yellow); }
</style>

// apps/web/src/components/ui/card.tsx
'use client'

import { type HTMLAttributes } from 'react'
import { cn } from '@/lib/cn'

type CardVariant = 'default' | 'flat' | 'elevated' | 'interactive'
type Accent = 'coral' | 'turquoise' | 'yellow' | null
type Padding = 'none' | 'sm' | 'md' | 'lg'

interface CardProps extends HTMLAttributes<HTMLDivElement> {
  variant?: CardVariant
  accent?: Accent
  padding?: Padding
}

const variantStyles: Record<CardVariant, string> = {
  default: 'shadow-[var(--shadow-brutal)]',
  flat: 'shadow-none',
  elevated: 'shadow-[var(--shadow-brutal-lg)] hover:shadow-[var(--shadow-brutal-md)]',
  interactive:
    'shadow-[var(--shadow-brutal)] cursor-pointer hover:shadow-[var(--shadow-brutal-md)] active:shadow-[var(--shadow-brutal-sm)] transition-shadow duration-200',
}

const accentStyles: Record<string, string> = {
  coral: 'border-l-[3px] border-l-[var(--color-coral)]',
  turquoise: 'border-l-[3px] border-l-[var(--color-turquoise)]',
  yellow: 'border-l-[3px] border-l-[var(--color-yellow)]',
}

const paddingStyles: Record<Padding, string> = {
  none: 'p-0',
  sm: 'p-3',
  md: 'p-4',
  lg: 'p-6',
}

export function Card({
  variant = 'default',
  accent,
  padding = 'md',
  className,
  children,
  ...props
}: CardProps) {
  return (
    <div
      className={cn(
        'bg-[var(--color-surface)] border border-[var(--color-border)] rounded-[var(--radius-md)]',
        variantStyles[variant],
        accent && accentStyles[accent],
        paddingStyles[padding],
        className,
      )}
      {...props}
    >
      {children}
    </div>
  )
}
