// apps/web/src/app/(app)/dashboard/page.tsx
'use client'

import { useEffect, useMemo, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import Link from 'next/link'
import { useProblems } from '@/hooks/use-problems'
import { useProgress } from '@/hooks/use-progress'
import { Badge } from '@/components/ui/badge'
import { Skeleton } from '@/components/ui/skeleton'
import { EmptyState } from '@/components/ui/empty-state'
import { Dropdown } from '@/components/ui/dropdown'
import { Input } from '@/components/ui/input'
import { getProblemSlug } from '@/lib/problem-utils'
import type { Problem } from '@/types'
import { cn } from '@/lib/cn'

type DifficultyFilter = 'All' | 'Easy' | 'Medium' | 'Hard'
type SortOption = 'recommended' | 'difficulty' | 'title'
type StatusFilter = 'all' | 'todo' | 'attempted' | 'solved'

const difficultyTone = { Easy: 'easy', Medium: 'medium', Hard: 'hard' } as const

function useDebounce<T>(value: T, delay: number): T {
  const [debounced, setDebounced] = useState(value)
  useEffect(() => {
    const id = setTimeout(() => setDebounced(value), delay)
    return () => clearTimeout(id)
  }, [value, delay])
  return debounced
}

export default function DashboardPage() {
  const { data: problems, isLoading, isError } = useProblems()
  const { isCompleted, isAttempted, completedCount } = useProgress()

  const [search, setSearch] = useState('')
  const [difficulty, setDifficulty] = useState<DifficultyFilter>('All')
  const [sortBy, setSortBy] = useState<SortOption>('recommended')
  const [statusFilter, setStatusFilter] = useState<StatusFilter>('all')

  const debouncedSearch = useDebounce(search, 220)

  const enriched = useMemo(() => {
    if (!problems) return []
    return problems.map((p) => ({
      ...p,
      status: isCompleted(p.id) ? 'solved' : isAttempted(p.id) ? 'attempted' : 'todo',
      slug: getProblemSlug(p),
    }))
  }, [problems, isCompleted, isAttempted])

  const filtered = useMemo(() => {
    let list = enriched.filter((p) => {
      const q = debouncedSearch.toLowerCase()
      const matchSearch = !q || p.title.toLowerCase().includes(q) || p.categories.some((c) => c.toLowerCase().includes(q))
      const matchDiff = difficulty === 'All' || p.difficulty === difficulty
      const matchStatus = statusFilter === 'all' || p.status === statusFilter
      return matchSearch && matchDiff && matchStatus
    })

    if (sortBy === 'difficulty') {
      const order = { Easy: 1, Medium: 2, Hard: 3 }
      list = [...list].sort((a, b) => order[a.difficulty] - order[b.difficulty])
    } else if (sortBy === 'title') {
      list = [...list].sort((a, b) => a.title.localeCompare(b.title))
    } else {
      const sRank = { solved: 2, attempted: 1, todo: 0 }
      list = [...list].sort((a, b) => sRank[a.status as keyof typeof sRank] - sRank[b.status as keyof typeof sRank] || a.id - b.id)
    }

    return list
  }, [enriched, debouncedSearch, difficulty, sortBy, statusFilter])

  const totalCount = problems?.length ?? 0
  const progressPct = totalCount ? Math.round((completedCount / totalCount) * 100) : 0

  return (
    <div className="py-6 grid gap-6">
      {/* Header */}
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div>
          <h1 className="font-[family-name:var(--font-display)] font-bold text-2xl text-[var(--color-text-primary)]">
            Problems
          </h1>
          <p className="text-sm text-[var(--color-text-secondary)] mt-1">
            {completedCount} / {totalCount} solved · {progressPct}% complete
          </p>
        </div>
        <div className="w-full sm:w-40 h-1.5 self-center rounded-[var(--radius-full)] bg-[var(--color-surface)] overflow-hidden">
          <div
            className="h-full bg-[var(--color-success)] rounded-[var(--radius-full)] transition-all duration-500"
            style={{ width: `${progressPct}%` }}
          />
        </div>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap gap-3 items-end">
        <div className="flex-1 min-w-[180px]">
          <Input
            as="input"
            type="text"
            placeholder="Search problems…"
            value={search}
            onChange={(e) => setSearch((e.target as HTMLInputElement).value)}
          />
        </div>
        <Dropdown
          className="w-36"
          items={[
            { value: 'All', label: 'All difficulties' },
            { value: 'Easy', label: 'Easy' },
            { value: 'Medium', label: 'Medium' },
            { value: 'Hard', label: 'Hard' },
          ]}
          value={difficulty}
          onChange={(v) => setDifficulty(v as DifficultyFilter)}
        />
        <Dropdown
          className="w-40"
          items={[
            { value: 'recommended', label: 'Recommended' },
            { value: 'difficulty', label: 'Difficulty' },
            { value: 'title', label: 'Title A–Z' },
          ]}
          value={sortBy}
          onChange={(v) => setSortBy(v as SortOption)}
        />
        <Dropdown
          className="w-36"
          items={[
            { value: 'all', label: 'All status' },
            { value: 'todo', label: 'To do' },
            { value: 'attempted', label: 'Attempted' },
            { value: 'solved', label: 'Solved' },
          ]}
          value={statusFilter}
          onChange={(v) => setStatusFilter(v as StatusFilter)}
        />
      </div>

      {/* List */}
      {isLoading ? (
        <div className="grid gap-2">
          {Array.from({ length: 8 }).map((_, i) => (
            <Skeleton key={i} height={56} />
          ))}
        </div>
      ) : isError ? (
        <EmptyState
          title="Failed to load problems"
          description="Something went wrong. Please try again."
          action={<button type="button" onClick={() => window.location.reload()} className="px-4 py-2 text-sm font-medium border border-[var(--color-border)] rounded-[var(--radius-md)] bg-[var(--color-surface-raised)] text-[var(--color-text-primary)] hover:bg-[var(--color-surface)] transition-colors">Retry</button>}
        />
      ) : filtered.length === 0 ? (
        <EmptyState
          title="No problems found"
          description="Try adjusting your filters or search query."
        />
      ) : (
        <div className="grid gap-1.5">
          <AnimatePresence initial={false}>
            {filtered.map((p, i) => (
              <motion.div
                key={p.id}
                layout
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -4 }}
                transition={{ duration: 0.18, delay: i * 0.03, ease: [0.25, 0.46, 0.45, 0.94] }}
              >
                <ProblemRow problem={p} status={p.status} />
              </motion.div>
            ))}
          </AnimatePresence>
        </div>
      )}
    </div>
  )
}

function ProblemRow({
  problem,
  status,
}: {
  problem: Problem & { slug: string }
  status: string
}) {
  const statusIcon = status === 'solved' ? '✓' : status === 'attempted' ? '·' : ''

  return (
    <Link
      href={`/practice/${problem.slug}`}
      className={cn(
        'flex items-center gap-4 px-4 py-3 rounded-[var(--radius-md)]',
        'border border-[var(--color-border)] bg-[var(--color-surface)]',
        'hover:bg-[var(--color-surface-raised)] hover:shadow-[var(--shadow-brutal-sm)]',
        'transition-all duration-[var(--duration-fast)] no-underline group',
      )}
    >
      <span className="w-5 text-center font-[family-name:var(--font-mono)] text-xs text-[var(--color-text-tertiary)]">
        {statusIcon || problem.id}
      </span>
      <span className="flex-1 text-sm font-medium text-[var(--color-text-primary)] group-hover:text-[var(--color-primary)] transition-colors">
        {problem.title}
      </span>
      <div className="hidden sm:flex gap-1.5">
        {problem.categories.slice(0, 2).map((c) => (
          <Badge key={c} tone="neutral" size="sm">{c}</Badge>
        ))}
      </div>
      <Badge tone={difficultyTone[problem.difficulty]} size="sm">
        {problem.difficulty}
      </Badge>
    </Link>
  )
}

// src/views/Dashboard.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { problems } from '../data/problems'
import { useProblemProgress } from '../composables/useProblemProgress'
import { useTheme } from '../composables/useTheme'
import { getProblemSlug } from '../utils/problemUtils'
import PageShell from '../components/shared/PageShell.vue'
import DashboardTopBar from '../components/dashboard/DashboardTopBar.vue'
import DailyChallengeCard from '../components/dashboard/DailyChallengeCard.vue'
import VirtualProblemList, { type VirtualProblemItem } from '../components/dashboard/VirtualProblemList.vue'
import BrutalCard from '../components/brutal/BrutalCard.vue'
import BrutalCheckbox from '../components/brutal/BrutalCheckbox.vue'
import BrutalEmptyState from '../components/brutal/BrutalEmptyState.vue'
import BrutalButton from '../components/brutal/BrutalButton.vue'
import BrutalProgress from '../components/brutal/BrutalProgress.vue'

const router = useRouter()
const { attempts, isCompleted, completedCount } = useProblemProgress()
const { theme, toggleTheme } = useTheme()

const searchInput = ref('')
const searchQuery = ref('')
let debounceTimer: ReturnType<typeof setTimeout> | null = null

watch(searchInput, (value) => {
  if (debounceTimer) clearTimeout(debounceTimer)
  debounceTimer = setTimeout(() => {
    searchQuery.value = value.trim()
  }, 220)
})

const selectedDifficulty = ref<'All' | 'Easy' | 'Medium' | 'Hard'>('All')
const sortBy = ref('recommended')
const statusFilter = ref<'all' | 'todo' | 'attempted' | 'solved'>('all')
const selectedCategories = ref<string[]>([])
const filterRailOpen = ref(false)

const categories = computed(() => {
  return [...new Set(problems.flatMap(problem => problem.categories))].sort((a, b) => a.localeCompare(b))
})

const totalProblems = computed(() => problems.length)
const progressPercent = computed(() => Math.round((completedCount.value / totalProblems.value) * 100))

const problemStatus = (problemId: number): 'todo' | 'attempted' | 'solved' => {
  if (isCompleted(problemId)) return 'solved'
  if (attempts.value[problemId]) return 'attempted'
  return 'todo'
}

const acceptanceFor = (problemId: number) => {
  return Math.min(94, 46 + ((problemId * 7) % 42))
}

const enrichedProblems = computed<VirtualProblemItem[]>(() => {
  return problems.map(problem => ({
    id: problem.id,
    title: problem.title,
    difficulty: problem.difficulty,
    categories: problem.categories,
    acceptance: acceptanceFor(problem.id),
    status: problemStatus(problem.id),
  }))
})

const filteredProblems = computed(() => {
  let list = enrichedProblems.value.filter(problem => {
    const matchesSearch =
      problem.title.toLowerCase().includes(searchQuery.value.toLowerCase()) ||
      problem.categories.some(category => category.toLowerCase().includes(searchQuery.value.toLowerCase()))

    const matchesDifficulty =
      selectedDifficulty.value === 'All' || problem.difficulty === selectedDifficulty.value

    const matchesStatus = statusFilter.value === 'all' || problem.status === statusFilter.value

    const matchesCategory =
      selectedCategories.value.length === 0 ||
      selectedCategories.value.every(category => problem.categories.includes(category))

    return matchesSearch && matchesDifficulty && matchesStatus && matchesCategory
  })

  if (sortBy.value === 'difficulty') {
    const order = { Easy: 1, Medium: 2, Hard: 3 }
    list = [...list].sort((a, b) => order[a.difficulty] - order[b.difficulty])
  }

  if (sortBy.value === 'acceptance') {
    list = [...list].sort((a, b) => b.acceptance - a.acceptance)
  }

  if (sortBy.value === 'title') {
    list = [...list].sort((a, b) => a.title.localeCompare(b.title))
  }

  if (sortBy.value === 'recommended') {
    const statusRank = { solved: 2, attempted: 1, todo: 0 }
    list = [...list].sort((a, b) => statusRank[a.status] - statusRank[b.status] || a.id - b.id)
  }

  return list
})

const dailyChallenge = computed(() => {
  const next = enrichedProblems.value.find(problem => problem.status !== 'solved')
  if (!next) return null
  return problems.find(problem => problem.id === next.id) ?? null
})

const startProblem = (problemId: number) => {
  const problem = problems.find(item => item.id === problemId)
  if (!problem) return
  router.push(`/practice/${getProblemSlug(problem)}`)
}

const toggleCategory = (category: string) => {
  if (selectedCategories.value.includes(category)) {
    selectedCategories.value = selectedCategories.value.filter(value => value !== category)
  } else {
    selectedCategories.value = [...selectedCategories.value, category]
  }
}

const clearFilters = () => {
  searchInput.value = ''
  searchQuery.value = ''
  selectedDifficulty.value = 'All'
  statusFilter.value = 'all'
  selectedCategories.value = []
}

const goProfile = () => router.push('/profile')
const goLeaderboard = () => router.push('/leaderboard')

const updateSearchQuery = (value: string) => {
  searchInput.value = value
}

const updateDifficulty = (value: 'All' | 'Easy' | 'Medium' | 'Hard') => {
  selectedDifficulty.value = value
}

const updateSort = (value: string) => {
  sortBy.value = value
}
</script>

<template>
  <PageShell>
    <div class="dashboard-grid">
      <DashboardTopBar
        :search-query="searchInput"
        :selected-difficulty="selectedDifficulty"
        :sort-by="sortBy"
        :mobile-filters-open="filterRailOpen"
        @update:search-query="updateSearchQuery"
        @update:selected-difficulty="updateDifficulty"
        @update:sort-by="updateSort"
        @toggle-filters="filterRailOpen = !filterRailOpen"
        @open-profile="goProfile"
        @open-leaderboard="goLeaderboard"
      />

      <aside
        id="dashboard-filter-rail"
        class="filter-rail"
        :class="{ 'filter-rail--open': filterRailOpen }"
      >
        <BrutalCard variant="flat" padding="lg">
          <div class="rail-section">
            <h2 class="rail-title">Status</h2>
            <div class="rail-checks">
              <BrutalCheckbox
                :model-value="statusFilter === 'all'"
                label="All"
                @update:model-value="statusFilter = 'all'"
              />
              <BrutalCheckbox
                :model-value="statusFilter === 'todo'"
                label="Todo"
                @update:model-value="statusFilter = 'todo'"
              />
              <BrutalCheckbox
                :model-value="statusFilter === 'attempted'"
                label="Attempted"
                @update:model-value="statusFilter = 'attempted'"
              />
              <BrutalCheckbox
                :model-value="statusFilter === 'solved'"
                label="Solved"
                @update:model-value="statusFilter = 'solved'"
              />
            </div>
          </div>

          <div class="rail-section">
            <h2 class="rail-title">Categories</h2>
            <div class="category-grid">
              <button
                v-for="category in categories"
                :key="category"
                class="category-chip"
                :class="{ 'category-chip--active': selectedCategories.includes(category) }"
                @click="toggleCategory(category)"
              >
                {{ category }}
              </button>
            </div>
          </div>

          <BrutalButton variant="ghost" size="sm" @click="clearFilters">Reset Filters</BrutalButton>
        </BrutalCard>

        <DailyChallengeCard :problem="dailyChallenge" @start="startProblem" />
      </aside>

      <main class="dashboard-main">
        <BrutalCard variant="flat" padding="lg">
          <div class="progress-row">
            <div>
              <p class="progress-title">Progress</p>
              <p class="progress-copy">{{ completedCount }}/{{ totalProblems }} solved</p>
            </div>

            <BrutalButton variant="secondary" size="sm" @click="toggleTheme">
              Theme: {{ theme }}
            </BrutalButton>
          </div>

          <BrutalProgress variant="bar" :value="progressPercent" :max="100" />
        </BrutalCard>

        <VirtualProblemList
          v-if="filteredProblems.length"
          :items="filteredProblems"
          :viewport-height="620"
          @select="startProblem"
        />

        <BrutalEmptyState
          v-else
          title="No matching problems"
          description="Try a broader search or relax category filters."
          action-label="Clear filters"
          @action="clearFilters"
        />
      </main>
    </div>
  </PageShell>
</template>

<style scoped>
.dashboard-grid {
  display: grid;
  grid-template-columns: minmax(14rem, 18.5rem) minmax(0, 1fr);
  grid-template-areas:
    'topbar topbar'
    'rail main';
  gap: 0.8rem;
  padding-bottom: 2rem;
}

:deep(.dashboard-topbar) {
  grid-area: topbar;
}

.filter-rail {
  grid-area: rail;
  display: grid;
  gap: 0.75rem;
  align-self: start;
}

.dashboard-main {
  grid-area: main;
  display: grid;
  gap: 0.75rem;
}

.rail-section {
  display: grid;
  gap: 0.45rem;
}

.rail-title {
  margin: 0;
  font-family: var(--font-display);
  font-size: var(--text-lg);
}

.rail-checks {
  display: grid;
  gap: 0.35rem;
}

.category-grid {
  display: flex;
  gap: 0.35rem;
  flex-wrap: wrap;
}

.category-chip {
  border: 2px solid var(--color-border-strong);
  border-radius: var(--radius-sm);
  background: var(--color-surface-raised);
  box-shadow: 1px 1px 0 0 var(--color-shadow-strong);
  font-size: var(--text-xs);
  font-family: var(--font-mono);
  padding: 0.24rem 0.4rem;
  cursor: pointer;
}

.category-chip--active {
  background: var(--color-yellow);
  color: var(--color-accent-ink);
}

.progress-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 0.5rem;
  margin-bottom: 0.7rem;
}

.progress-title {
  margin: 0;
  font-family: var(--font-display);
  font-size: var(--text-xl);
}

.progress-copy {
  margin: 0.2rem 0 0;
  color: var(--color-text-secondary);
}

@media (max-width: 1000px) {
  .dashboard-grid {
    grid-template-columns: 1fr;
    grid-template-areas:
      'topbar'
      'rail'
      'main';
  }

  .filter-rail {
    display: none;
  }

  .filter-rail--open {
    display: grid;
  }
}
</style>
