// apps/web/src/app/(app)/leaderboard/page.tsx
'use client'

import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { useAuth } from '@/hooks/use-auth'
import { api } from '@/lib/api-client'
import { Tabs } from '@/components/ui/tabs'
import { Skeleton } from '@/components/ui/skeleton'
import { EmptyState } from '@/components/ui/empty-state'
import { LeaderboardEntrySchema, type LeaderboardEntry } from '@/types/api'
import { z } from 'zod'
import { cn } from '@/lib/cn'

const TABS = [
  { id: 'global', label: 'Global' },
  { id: 'weighted', label: 'Weighted' },
  { id: 'hard', label: 'Hard Focus' },
]

export default function LeaderboardPage() {
  const { user } = useAuth()
  const [tab, setTab] = useState('global')
  const [search, setSearch] = useState('')
  const [showOnlyMe, setShowOnlyMe] = useState(false)

  const { data: entries = [], isLoading, isError } = useQuery<LeaderboardEntry[]>({
    queryKey: ['leaderboard', tab],
    queryFn: async () => {
      const data = await api.get<unknown[]>(`/leaderboard?type=${tab}`)
      return z.array(LeaderboardEntrySchema).parse(data)
    },
    staleTime: 60_000,
  })

  const filtered = entries.filter((e) => {
    if (showOnlyMe && user) return e.username === user.username
    if (search) return e.username.toLowerCase().includes(search.toLowerCase())
    return true
  })

  const top3 = filtered.slice(0, 3)
  const rest = filtered.slice(3)

  return (
    <div className="py-6 grid gap-6">
      <div>
        <h1 className="font-[family-name:var(--font-display)] font-bold text-2xl text-[var(--color-text-primary)]">
          Leaderboard
        </h1>
        <p className="text-sm text-[var(--color-text-secondary)] mt-1">
          See how you rank against other coders.
        </p>
      </div>

      <Tabs value={tab} items={TABS} onChange={setTab} />

      {/* Search + toggle */}
      <div className="flex gap-3 items-center flex-wrap">
        <input
          type="text"
          placeholder="Search username…"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="flex-1 min-w-[160px] px-3 py-2 text-sm border border-[var(--color-border)] rounded-[var(--radius-md)] bg-[var(--color-surface-raised)] text-[var(--color-text-primary)] focus:outline-none focus:border-[var(--color-primary)] transition-colors"
        />
        {user && (
          <button
            type="button"
            onClick={() => setShowOnlyMe((s) => !s)}
            className={cn(
              'px-3 py-2 text-sm rounded-[var(--radius-md)] border transition-colors',
              showOnlyMe
                ? 'bg-[var(--color-primary)] text-[var(--button-primary-text)] border-[var(--color-primary)]'
                : 'bg-[var(--color-surface-raised)] text-[var(--color-text-secondary)] border-[var(--color-border)] hover:text-[var(--color-text-primary)]',
            )}
          >
            Only me
          </button>
        )}
      </div>

      {isLoading ? (
        <div className="grid gap-2">{Array.from({ length: 10 }).map((_, i) => <Skeleton key={i} height={48} />)}</div>
      ) : isError ? (
        <EmptyState
          title="Failed to load leaderboard"
          description="Something went wrong. Please try again."
          action={<button type="button" onClick={() => window.location.reload()} className="px-4 py-2 text-sm font-medium border border-[var(--color-border)] rounded-[var(--radius-md)] bg-[var(--color-surface-raised)] text-[var(--color-text-primary)] hover:bg-[var(--color-surface)] transition-colors">Retry</button>}
        />
      ) : filtered.length === 0 ? (
        <EmptyState title="No results" description="No entries match your search." />
      ) : (
        <>
          {/* Podium */}
          {top3.length >= 3 && (
            <div className="flex items-end justify-center gap-3 py-6">
              {[top3[1], top3[0], top3[2]].map((entry, i) => {
                const heights = ['h-20', 'h-28', 'h-16']
                const medals = ['🥈', '🥇', '🥉']
                return (
                  <div key={entry.userId} className={cn('flex flex-col items-center gap-2 flex-1 max-w-[7rem] bg-[var(--color-surface)] border border-[var(--color-border)] rounded-t-[var(--radius-md)]', heights[i])}>
                    <span className="mt-3 text-2xl">{medals[i]}</span>
                    <span className="text-xs font-semibold text-[var(--color-text-primary)] truncate px-1">{entry.username}</span>
                    <span className="text-xs text-[var(--color-text-secondary)]">{entry.problemsSolved}</span>
                  </div>
                )
              })}
            </div>
          )}

          {/* Table */}
          <div className="border border-[var(--color-border)] rounded-[var(--radius-md)] overflow-hidden">
            <div className="grid grid-cols-[2rem_1fr_5rem_4rem_4rem_4rem] gap-3 px-4 py-2.5 bg-[var(--color-surface)] border-b border-[var(--color-border)] text-xs font-semibold text-[var(--color-text-secondary)]">
              <span>#</span>
              <span>User</span>
              <span className="text-right">Solved</span>
              <span className="text-right">Easy</span>
              <span className="text-right">Med</span>
              <span className="text-right">Hard</span>
            </div>
            {filtered.map((entry) => (
              <div
                key={entry.userId}
                className={cn(
                  'grid grid-cols-[2rem_1fr_5rem_4rem_4rem_4rem] gap-3 px-4 py-3 border-b border-[var(--color-border)] text-sm transition-colors last:border-b-0',
                  entry.username === user?.username
                    ? 'bg-[var(--color-success-bg)]'
                    : 'hover:bg-[var(--color-surface-raised)]',
                )}
              >
                <span className="font-[family-name:var(--font-mono)] text-xs text-[var(--color-text-tertiary)]">{entry.rank}</span>
                <span className="font-medium text-[var(--color-text-primary)] truncate">{entry.username}</span>
                <span className="text-right font-bold text-[var(--color-text-primary)]">{entry.problemsSolved}</span>
                <span className="text-right text-[var(--color-success)]">{entry.easy}</span>
                <span className="text-right text-[var(--color-warning)]">{entry.medium}</span>
                <span className="text-right text-[var(--color-error)]">{entry.hard}</span>
              </div>
            ))}
          </div>
        </>
      )}
    </div>
  )
}

// src/views/Leaderboard.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { api } from '../api/client'
import { useAuth } from '../composables/useAuth'
import BrutalCard from '../components/brutal/BrutalCard.vue'
import BrutalTabs from '../components/brutal/BrutalTabs.vue'
import BrutalBadge from '../components/brutal/BrutalBadge.vue'
import BrutalButton from '../components/brutal/BrutalButton.vue'
import BrutalCheckbox from '../components/brutal/BrutalCheckbox.vue'
import BrutalInput from '../components/brutal/BrutalInput.vue'
import BrutalEmptyState from '../components/brutal/BrutalEmptyState.vue'
import BrutalSkeleton from '../components/brutal/BrutalSkeleton.vue'

interface LeaderboardApiItem {
  rank: number
  userId: number
  username: string
  problemsSolved: number
  easy: number
  medium: number
  hard: number
}

interface LeaderboardRow extends LeaderboardApiItem {
  score: number
  computedRank: number
}

const router = useRouter()
const { user } = useAuth()

const activeTab = ref<'global' | 'weighted' | 'hard'>('global')
const tabs = [
  { id: 'global', label: 'Global' },
  { id: 'weighted', label: 'Weighted' },
  { id: 'hard', label: 'Hard Focus' },
]

const showOnlyMe = ref(false)
const searchQuery = ref('')
const loading = ref(true)
const error = ref('')
const rows = ref<LeaderboardApiItem[]>([])

const fetchLeaderboard = async () => {
  loading.value = true
  error.value = ''

  try {
    const response = await api.get<{ leaderboard: LeaderboardApiItem[] }>('/leaderboard')
    rows.value = response.leaderboard
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to load leaderboard.'
    rows.value = []
  } finally {
    loading.value = false
  }
}

onMounted(fetchLeaderboard)

const scoreFor = (item: LeaderboardApiItem) => {
  if (activeTab.value === 'global') return item.problemsSolved
  if (activeTab.value === 'hard') return item.hard
  return item.hard * 5 + item.medium * 3 + item.easy
}

const rankedEntries = computed<LeaderboardRow[]>(() => {
  let list = rows.value
    .map(item => ({
      ...item,
      score: scoreFor(item),
    }))
    .filter(item => item.score > 0)

  if (searchQuery.value.trim()) {
    const query = searchQuery.value.trim().toLowerCase()
    list = list.filter(item => item.username.toLowerCase().includes(query))
  }

  if (showOnlyMe.value && user.value) {
    list = list.filter(item => item.userId === user.value?.id)
  }

  return list
    .sort((a, b) => {
      if (b.score !== a.score) return b.score - a.score
      if (b.hard !== a.hard) return b.hard - a.hard
      if (b.medium !== a.medium) return b.medium - a.medium
      return b.easy - a.easy
    })
    .map((item, index) => ({
      ...item,
      computedRank: index + 1,
    }))
})

const topThree = computed(() => rankedEntries.value.slice(0, 3))
const tableEntries = computed(() => rankedEntries.value.slice(3))

const currentUserId = computed(() => user.value?.id ?? null)

const goToDashboard = () => {
  router.push('/dashboard')
}

const scoreLabel = computed(() => {
  if (activeTab.value === 'global') return 'Solved'
  if (activeTab.value === 'hard') return 'Hard Solves'
  return 'Weighted Score'
})
</script>

<template>
  <div class="leaderboard">
    <div class="leaderboard__container">
      <header class="leaderboard__header">
        <div>
          <h1 class="leaderboard__title">Leaderboard</h1>
          <p class="leaderboard__subtitle">Live rankings from real solved progress. No seed data.</p>
        </div>

        <div class="leaderboard__header-actions">
          <BrutalButton variant="secondary" size="sm" @click="fetchLeaderboard">Refresh</BrutalButton>
          <BrutalButton variant="secondary" size="sm" @click="goToDashboard">Back to Dashboard</BrutalButton>
        </div>
      </header>

      <BrutalCard variant="flat" padding="lg">
        <div class="leaderboard__toolbar">
          <BrutalTabs v-model="activeTab" :items="tabs" />

          <div class="leaderboard__filters">
            <BrutalInput
              v-model="searchQuery"
              label="Find user"
              placeholder="username"
            />

            <BrutalCheckbox
              v-model="showOnlyMe"
              label="Show only me"
              :disabled="!user"
            />
          </div>
        </div>
      </BrutalCard>

      <template v-if="loading">
        <section class="podium">
          <BrutalCard v-for="idx in 3" :key="idx" variant="elevated" padding="lg">
            <div class="podium-skeleton">
              <BrutalSkeleton width="40%" height="1.8rem" />
              <BrutalSkeleton width="70%" height="1rem" />
              <BrutalSkeleton width="50%" height="1rem" />
            </div>
          </BrutalCard>
        </section>
      </template>

      <BrutalCard v-else-if="error" variant="flat" padding="lg">
        <BrutalEmptyState
          title="Could not load leaderboard"
          :description="error"
          action-label="Retry"
          @action="fetchLeaderboard"
        />
      </BrutalCard>

      <BrutalCard v-else-if="rankedEntries.length === 0" variant="flat" padding="lg">
        <BrutalEmptyState
          title="No leaderboard entries"
          description="No one has completed problems yet for this filter."
          action-label="Reset filters"
          @action="() => { searchQuery = ''; showOnlyMe = false }"
        />
      </BrutalCard>

      <template v-else>
        <section class="podium">
          <BrutalCard
            v-for="entry in topThree"
            :key="entry.userId"
            variant="elevated"
            padding="lg"
            :accent="entry.computedRank === 1 ? 'yellow' : entry.computedRank === 2 ? 'turquoise' : 'coral'"
          >
            <div class="podium-card" :class="`podium-card--${entry.computedRank}`">
              <p class="podium-rank">#{{ entry.computedRank }}</p>
              <p class="podium-name">{{ entry.computedRank === 1 ? '👑 ' : '' }}{{ entry.username }}</p>
              <p class="podium-score">{{ entry.score }} {{ scoreLabel.toLowerCase() }}</p>
              <p class="podium-meta">Hard {{ entry.hard }} · Medium {{ entry.medium }} · Easy {{ entry.easy }}</p>
            </div>
          </BrutalCard>
        </section>

        <BrutalCard variant="flat" padding="none">
          <table class="leaderboard-table">
            <thead>
              <tr>
                <th>Rank</th>
                <th>Coder</th>
                <th>{{ scoreLabel }}</th>
                <th>Breakdown</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              <tr
                v-for="entry in tableEntries"
                :key="entry.userId"
                :class="{ 'leaderboard-row--me': entry.userId === currentUserId }"
              >
                <td>#{{ entry.computedRank }}</td>
                <td>{{ entry.username }}</td>
                <td>{{ entry.score }}</td>
                <td>H{{ entry.hard }} · M{{ entry.medium }} · E{{ entry.easy }}</td>
                <td>
                  <BrutalBadge
                    variant="status"
                    :tone="entry.computedRank <= 10 ? 'success' : 'neutral'"
                  >
                    {{ entry.computedRank <= 10 ? 'Top 10' : 'Climbing' }}
                  </BrutalBadge>
                </td>
              </tr>
            </tbody>
          </table>
        </BrutalCard>
      </template>
    </div>
  </div>
</template>

<style scoped>
.leaderboard {
  min-height: 100vh;
  padding: 2rem 1rem 3rem;
}

.leaderboard__container {
  width: min(72rem, 100%);
  margin: 0 auto;
  display: grid;
  gap: 1rem;
}

.leaderboard__header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 0.9rem;
  flex-wrap: wrap;
}

.leaderboard__header-actions {
  display: flex;
  gap: 0.5rem;
  flex-wrap: wrap;
}

.leaderboard__title {
  font-family: var(--font-display);
  font-size: var(--text-4xl);
  line-height: 1;
  margin: 0;
}

.leaderboard__subtitle {
  margin-top: 0.35rem;
  color: var(--color-text-secondary);
}

.leaderboard__toolbar {
  display: grid;
  gap: 0.9rem;
}

.leaderboard__filters {
  display: grid;
  grid-template-columns: minmax(0, 1fr) auto;
  gap: 0.75rem;
  align-items: end;
}

.podium {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 0.75rem;
}

.podium-skeleton {
  display: grid;
  gap: 0.55rem;
}

.podium-card {
  text-align: center;
}

.podium-rank {
  font-family: var(--font-display);
  font-size: var(--text-3xl);
  font-weight: var(--font-weight-extrabold);
  line-height: 1;
  margin: 0;
}

.podium-name {
  margin-top: 0.35rem;
  font-weight: var(--font-weight-bold);
}

.podium-score {
  margin-top: 0.2rem;
  font-size: var(--text-xl);
  font-family: var(--font-display);
}

.podium-meta {
  margin-top: 0.2rem;
  color: var(--color-text-secondary);
  font-size: var(--text-sm);
}

.podium-card--1 {
  transform: translateY(-6px);
}

.leaderboard-table {
  width: 100%;
  border-collapse: collapse;
}

.leaderboard-table th,
.leaderboard-table td {
  padding: 0.65rem 0.85rem;
  text-align: left;
  border-bottom: 3px solid var(--color-border-subtle);
}

.leaderboard-table th {
  background: var(--color-background);
  font-size: var(--text-xs);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.leaderboard-table tbody tr:nth-child(odd) {
  background: rgba(255, 255, 255, 0.35);
}

.leaderboard-table tbody tr:hover {
  background: rgba(255, 230, 109, 0.24);
}

.leaderboard-row--me {
  background: rgba(255, 230, 109, 0.55) !important;
  font-weight: var(--font-weight-bold);
}

@media (max-width: 940px) {
  .podium {
    grid-template-columns: 1fr;
  }

  .leaderboard__filters {
    grid-template-columns: 1fr;
  }
}
</style>
